export const ERROR_TYPE_PRODUCT_CHECK = {
  INCORRECT_BODY: 'INCORRECT_BODY',
  INCORRECT_TYPE: 'INCORRECT_TYPE',
  MISSING_PROPERTY: 'MISSING_PROPERTY',
  NOT_FOUND: 'NOT_FOUND',
  INCORRECT_QUANTITY: 'INCORRECT_QUANTITY',
};

export const API_PRODUCTS = {
  CART: '/api/cart',
  PRODUCT_CHECK: '/api/product/check',
};
